sudo: false
language: rust
rust: nightly
os: linux
cache:
 directories:
  - $HOME/.cargo

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

matrix:
  include:
    - os: osx

before_script:
- |
  if [ -z ${INTEGRATION} ]; then
    if [ $TRAVIS_OS_NAME = 'osx' ]; then
      source env/bin/activate &&
      python --version &&
      pip install 'travis-cargo<0.2'
    else
      pip install 'travis-cargo<0.2' --user &&
      export PATH="$(python -m site --user-base)/bin:$PATH"
    fi
  fi

script:
  - |
    if [ -z ${INTEGRATION} ]; then
      cargo build
      cargo test
    else
      ./ci/integration.sh
    fi

after_success:
- if [ -z ${INTEGRATION} ]; then travis-cargo coveralls --no-sudo; fi

before_deploy:
  # TODO: cross build
 - cargo build --release --target=x86_64-unknown-linux-gnu
 - tar czf rustfmt-x86_64-unknown-linux-gnu.tar.gz Contributing.md Design.md README.md -C target/x86_64-unknown-linux-gnu/release/rustfmt rustfmt

deploy:
  provider: releases
  api_key:
    secure: "your own encrypted key"
  file:
  - rustfmt-x86_64-unknown-linux-gnu.tar.gz
  on:
    repo: nrc/rustfmt
    tags: true
    condition: "$DEPLOY = LINUX"
  skip_cleanup: true
